### ISSUE TITLE
Problem with Config.yml loading when under 1.17 version

### ISSUE THREAD

**Issue by HyperSkys** [puugz/bee#1]
Just tested this plugin for fun, when I try and use it on 1.17 (Should be Supported) it will fail to load because of a configuration error.

**Comment by HyperSkys** [comment]
Also found out the /bee command doesn't work at all because you forgot a description in the plugin.yml of the /bee command

**Comment by GrowlyX** [comment]
stfu

**Comment by GrowlyX** [comment]
puggy puggy

**Comment by puugz** [comment]
no

**Comment by GrowlyX** [comment]
hi nv6

**Comment by NoSequel** [comment]
hi growly how are you

**Comment by staudlol** [comment]
> hi growly how are you

Hey

**Comment by GrowlyX** [comment]
> hi growly how are you

good wbu

**Comment by GrowlyX** [comment]
> > hi growly how are you
> 
> Hey

hi stufd

**Comment by NoSequel** [comment]
> > hi growly how are you
> 
> good wbu

im good too wbu

**Comment by puugz** [comment]
yo whats up

**Comment by GrowlyX** [comment]
> > > hi growly how are you
> > 
> > 
> > good wbu
> 
> im good too wbu

not bad just laughing at this issue

**Comment by NoSequel** [comment]
> > > > hi growly how are you
> > > 
> > > 
> > > good wbu
> > 
> > 
> > im good too wbu
> 
> not bad just laughing at this issue

thats good wbu

**Comment by puugz** [comment]
hey growly how are you

**Comment by GrowlyX** [comment]
> hey growly how are you

not bad

**Comment by puugz** [comment]
wbu?

**Comment by GrowlyX** [comment]
do  you guys want to test out hyperskys' new plugin on mcm

**Comment by GrowlyX** [comment]
it's called buildmode-1.0-snapshot

**Comment by puugz** [comment]
🥶🥶

**Comment by GrowlyX** [comment]
he even included PROOF OF OWNERSHIP

**Comment by puugz** [comment]
bro its BUILDMODE-UPDATE.jar

**Comment by GrowlyX** [comment]
idk why anyone would want to claim that code as their own but you do you

**Comment by HyperSkys** [comment]
> idk why anyone would want to claim that code as their own but you do you
bro i was just pointing out a bug in his code, i mean atleast my plugin works his fails to even load cringe

**Comment by HyperSkys** [comment]
> he even included PROOF OF OWNERSHIP

just to get it accepted faster

**Comment by HyperSkys** [comment]
> do you guys want to test out hyperskys' new plugin on mcm

didn't you say u wanted to stay away from me, but it seems like you are obsessed with me I guess i have a new stalker thats cool

**Comment by HyperSkys** [comment]
> > > > hi growly how are you
> > > 
> > > 
> > > good wbu
> > 
> > 
> > im good too wbu
> 
> not bad just laughing at this issue

but it doesn't work i mean why would you be laughing

**Comment by HyperSkys** [comment]
> he even included PROOF OF OWNERSHIP

also why were you trying to use melons maps for your "pvp.bar" do you not even have a builder that can make a map for you?

**Comment by HyperSkys** [comment]
> idk why anyone would want to claim that code as their own but you do you

I mean I wouldn't be using the skidded TPSManager off bukkit on scandium bro cringe
